### ISSUE TITLE
Cannot undone media file in item

### ISSUE THREAD

**Issue by joniahola** [microfeed/microfeed#9]
I added external url to a post. Then I wanted remove that url in the post. But it's still show website homepage's url. Seems like default value is website homepage when field is empty.

**Comment by wenbinf** [comment]
can you provide screenshot to help explain? thanks


specifically, what do you mean by "But it's still show website homepage's url."? where do you see the url? a specific rss field? or a link on website?

**Comment by joniahola** [comment]
I translate theme to finnish but i can translate.

Screenshot to admin section:
![image](https://user-images.githubusercontent.com/1186126/209829651-db547245-18ef-4159-9f25-59bf8ba5d1c4.png)

Then in website:
![image](https://user-images.githubusercontent.com/1186126/209829764-c5f40796-99a8-498f-a569-51bb0a0c891e.png)

This "Linkki" means to external url to english. 

First I added that external url what I talk about this post but then I decided that I don't want to use it before content description.

**Comment by wenbinf** [comment]
Thanks for the details, @joniahola !

Confirmed. It's a bug on our end for not handling blank external url correctly.

Now it should be fixed with https://github.com/microfeed/microfeed/pull/10

Please sync in your forked repo and re-deploy the code from GitHub Actions:

![image](https://user-images.githubusercontent.com/1719237/209886534-1abcf184-7f0b-410d-a377-d8ffd6d29853.png)

Let me know if you have further questions.

**Comment by joniahola** [comment]
Thanks! Now it's working properly

**Comment by joniahola** [comment]
@wenbinf I don't create new issue because it's almost same issue. 

If you add external url and save. Then clear external url field and save, it still show article list in admin. So this same problem it also in that post list.

![image](https://user-images.githubusercontent.com/1186126/209945013-bcc0fbb8-422a-4175-8f3a-6b2181771028.png)

**Comment by wenbinf** [comment]
> Look media file column in list

Yes. One more edge case to fix :)

This should be fixed by https://github.com/microfeed/microfeed/pull/12 
Please sync & re-deploy code.

**Comment by joniahola** [comment]
Nice, thanks! Tested
